<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\**" />
    <EmbeddedResource Remove="Core\**" />
    <None Remove="Core\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CodeAnalysis\Syntax\Parser\_deprecated\" />
  </ItemGroup>

</Project>
