<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="systemfiles\commands\help\help\**" />
    <Compile Remove="user\**" />
    <EmbeddedResource Remove="systemfiles\commands\help\help\**" />
    <EmbeddedResource Remove="user\**" />
    <None Remove="systemfiles\commands\help\help\**" />
    <None Remove="user\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="docs\" />
    <Folder Include="language\tokens\" />
    <Folder Include="systemfiles\commands\help\" />
    <Folder Include="systemfiles\commands\ls\" />
    <Folder Include="systemfiles\config\" />
    <Folder Include="systemfiles\paths\" />
    <Folder Include="main\" />
    <Folder Include="tests\" />
    <Folder Include="users\commands\" />
  </ItemGroup>

</Project>
