public enum SpecialType
{
    None = 0,
    System_Object,
    System_Enum,
    System_MulticastDelegate,
    System_Delegate,
    System_ValueType,
    System_Void,
    System_Boolean,
    System_Char,
    System_SByte,
    System_Byte,
    System_Int16,
    System_UInt16,
    System_Int32,
    System_UInt32,
    System_Int64,
    System_UInt64,
    System_Decimal,
    System_Single,
    System_Double,
    System_String,
    System_Array,
    System_IntPtr,
    System_UIntPtr,
    //System_Collections_IEnumerable,
    //System_Collections_Generic_IEnumerable_T,
    //System_Collections_Generic_IList_T,
    //System_Collections_Generic_ICollection_T,
    //System_Collections_IEnumerator,
    //System_Collections_Generic_IEnumerator_T,
    //System_Collections_Generic_IReadOnlyList_T,
    //System_Collections_Generic_IReadOnlyCollection_T,
    //System_Nullable_T,
    //System_DateTime,
    //System_Runtime_CompilerServices_IsVolatile,
    //System_IDisposable,
    //System_TypedReference,
    //System_ArgIterator,
    //System_RuntimeArgumentHandle,
    //System_RuntimeFieldHandle,
    //System_RuntimeMethodHandle,
    //System_RuntimeTypeHandle,
    //System_IAsyncResult,
    //System_AsyncCallback,
    //System_Runtime_CompilerServices_RuntimeFeature,
    //System_Runtime_CompilerServices_PreserveBaseOverridesAttribute,
}

//public enum SpecialType
//{
//    None = 0,
//    System_Object = 1,
//    System_Enum = 2,
//    System_MulticastDelegate = 3,
//    System_Delegate = 4,
//    System_ValueType = 5,
//    System_Void = 6,
//    System_Boolean = 7,
//    System_Char = 8,
//    System_SByte = 9,
//    System_Byte = 10,
//    System_Int16 = 11,
//    System_UInt16 = 12,
//    System_Int32 = 13,
//    System_UInt32 = 14,
//    System_Int64 = 15,
//    System_UInt64 = 16,
//    System_Decimal = 17,
//    System_Single = 18,
//    System_Double = 19,
//    System_String = 20,
//    System_IntPtr = 21,
//    System_UIntPtr = 22,
//    System_Array = 23,
//    System_Collections_IEnumerable = 24,
//    System_Collections_Generic_IEnumerable_T = 25,
//    System_Collections_Generic_IList_T = 26,
//    System_Collections_Generic_ICollection_T = 27,
//    System_Collections_IEnumerator = 28,
//    System_Collections_Generic_IEnumerator_T = 29,
//    System_Collections_Generic_IReadOnlyList_T = 30,
//    System_Collections_Generic_IReadOnlyCollection_T = 31,
//    System_Nullable_T = 32,
//    System_DateTime = 33,
//    System_Runtime_CompilerServices_IsVolatile = 34,
//    System_IDisposable = 35,
//    System_TypedReference = 36,
//    System_ArgIterator = 37,
//    System_RuntimeArgumentHandle = 38,
//    System_RuntimeFieldHandle = 39,
//    System_RuntimeMethodHandle = 40,
//    System_RuntimeTypeHandle = 41,
//    System_IAsyncResult = 42,
//    System_AsyncCallback = 43,
//    System_Runtime_CompilerServices_RuntimeFeature = 44,
//    System_Runtime_CompilerServices_PreserveBaseOverridesAttribute = 45
//}

//namespace Minsk.Core.Types;

//public enum SpecialType
//{
//    None = 0,
//    Char,
//    Bool,
//    Byte,
//    SByte,
//    Short,
//    UShort,
//    Int,
//    UInt,
//    Long,
//    ULong,
//    Float,
//    Double,
//    Decimal,
//    String,
//    Object,
//    Void
//}